import { FieldSlot, Player } from "@/components/ui/player-button";

export const MOCK_TEAMS = ["Corinthians", "Santos"];

export const MOCK_EDITIONS = ["2012"];

export const ALL_POSITIONS = [
  "GOL",
  "LD",
  "ZAG",
  "LE",
  "VOL",
  "MC",
  "MEI",
  "MD",
  "ME",
  "PD",
  "PE",
  "CA",
];

const POSITION_ORDER: Record<string, number> = {
  GOL: 1,
  LD: 2,
  ZAG: 3,
  LE: 4,
  VOL: 5,
  MC: 6,
  MEI: 7,
  MD: 8,
  ME: 9,
  PD: 10,
  PE: 11,
  CA: 12,
};

export const NAMES_BY_TEAM: Record<string, string[]> = {
  Corinthians: [
    "Cássio",
    "Júlio César",
    "Danilo Fernandes",
    "Alessandro",
    "Welder",
    "Chicão",
    "L. Castán",
    "Paulo André",
    "Marquinhos",
    "Fábio Santos",
    "Ramon",
    "Ralf",
    "Paulinho",
    "Edenílson",
    "Ramírez",
    "Danilo",
    "Douglas",
    "Alex",
    "Willian",
    "J. Henrique",
    "E. Sheik",
    "Romarinho",
    "Liédson",
    "Élton",
    "Gilsinho",
  ],
  Santos: [
    "Rafael",
    "Aranha",
    "Vladimir",
    "Fucile",
    "Galhardo",
    "Edu Dracena",
    "Durval",
    "Bruno Rodrigo",
    "Léo",
    "Juan",
    "Arouca",
    "Henrique",
    "Adriano",
    "Ibson",
    "Elano",
    "Ganso",
    "F. Anderson",
    "G. Magrão",
    "Bernardo",
    "Neymar",
    "Borges",
    "Alan Kardec",
    "Dimba",
    "W. Rentería",
    "Maranhão",
  ],
};

export const NUMBERS_BY_PLAYER: Record<string, number> = {
  "Júlio César": 1,
  Alessandro: 2,
  Chicão: 3,
  "L. Castán": 4,
  Ralf: 5,
  "Fábio Santos": 6,
  Willian: 7,
  Paulinho: 8,
  Liédson: 9,
  Douglas: 10,
  "E. Sheik": 11,
  Alex: 12,
  "Paulo André": 13,
  Ramírez: 14,
  Edenílson: 15,
  Ramon: 16,
  Gilsinho: 17,
  Welder: 18,
  Élton: 19,
  Danilo: 20,
  Romarinho: 21,
  "Danilo Fernandes": 22,
  "J. Henrique": 23,
  Cássio: 24,
  Marquinhos: 25,
  Rafael: 1,
  "Edu Dracena": 2,
  Léo: 3,
  Fucile: 4,
  Arouca: 5,
  Durval: 6,
  Henrique: 7,
  Elano: 8,
  Borges: 9,
  Ganso: 10,
  Neymar: 11,
  Aranha: 12,
  "Bruno Rodrigo": 13,
  Ibson: 14,
  Juan: 15,
  Adriano: 16,
  "G. Magrão": 17,
  Bernardo: 18,
  "Alan Kardec": 19,
  "F. Anderson": 20,
  Dimba: 21,
  Vladimir: 22,
  Galhardo: 23,
  "W. Rentería": 24,
  Maranhão: 25,
};

export const RATINGS_BY_PLAYER: Record<string, number> = {
  Cássio: 85,
  "Júlio César": 74,
  "Danilo Fernandes": 71,
  Alessandro: 78,
  Welder: 72,
  Chicão: 81,
  "L. Castán": 83,
  "Paulo André": 79,
  Marquinhos: 74,
  "Fábio Santos": 80,
  Ramon: 73,
  Ralf: 84,
  Paulinho: 87,
  Edenílson: 76,
  Ramírez: 74,
  Danilo: 85,
  Douglas: 79,
  Alex: 82,
  Willian: 78,
  "J. Henrique": 80,
  "E. Sheik": 86,
  Romarinho: 78,
  Liédson: 77,
  Élton: 73,
  Gilsinho: 72,
  Rafael: 82,
  Aranha: 75,
  Vladimir: 70,
  Fucile: 78,
  Galhardo: 73,
  "Edu Dracena": 81,
  Durval: 79,
  "Bruno Rodrigo": 76,
  Léo: 77,
  Juan: 75,
  Arouca: 83,
  Henrique: 80,
  Adriano: 76,
  Ibson: 77,
  Elano: 79,
  Ganso: 84,
  "F. Anderson": 75,
  "G. Magrão": 73,
  Bernardo: 74,
  Neymar: 92,
  Borges: 80,
  "Alan Kardec": 79,
  Dimba: 70,
  "W. Rentería": 72,
  Maranhão: 71,
};

export const POSITIONS_BY_PLAYER: Record<string, string[]> = {
  Cássio: ["GOL"],
  "Júlio César": ["GOL"],
  "Danilo Fernandes": ["GOL"],
  Alessandro: ["LD"],
  Welder: ["LD"],
  Chicão: ["ZAG"],
  "L. Castán": ["ZAG"],
  "Paulo André": ["ZAG"],
  Marquinhos: ["ZAG"],
  "Fábio Santos": ["LE"],
  Ramon: ["LE"],
  Ralf: ["VOL"],
  Paulinho: ["VOL", "MC"],
  Edenílson: ["VOL", "LD", "MD"],
  Ramírez: ["MEI", "MC"],
  Danilo: ["MEI", "MC"],
  Douglas: ["MEI"],
  Alex: ["MEI"],
  Willian: ["PE", "PD"],
  "J. Henrique": ["PD", "MD"],
  "E. Sheik": ["PE", "CA", "PD"],
  Romarinho: ["PE", "CA"],
  Liédson: ["CA"],
  Élton: ["CA"],
  Gilsinho: ["PD", "PE"],
  Rafael: ["GOL"],
  Aranha: ["GOL"],
  Vladimir: ["GOL"],
  Fucile: ["LD", "LE"],
  Galhardo: ["LD"],
  "Edu Dracena": ["ZAG"],
  Durval: ["ZAG", "LE"],
  "Bruno Rodrigo": ["ZAG"],
  Léo: ["LE"],
  Juan: ["LE"],
  Arouca: ["VOL", "MC"],
  Henrique: ["VOL", "ZAG"],
  Adriano: ["VOL"],
  Ibson: ["VOL", "MC"],
  Elano: ["MEI", "MC"],
  Ganso: ["MEI"],
  "F. Anderson": ["MEI"],
  "G. Magrão": ["MEI", "VOL"],
  Bernardo: ["MEI", "PE"],
  Neymar: ["PE", "CA", "PD"],
  Borges: ["CA"],
  "Alan Kardec": ["CA"],
  Dimba: ["CA"],
  "W. Rentería": ["CA", "PD"],
  Maranhão: ["MD", "LD"],
};

export const TACTICS: Record<
  string,
  Record<string, Omit<FieldSlot, "player">[]>
> = {
  "4-3-3": {
    Retranca: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "LD", x: 86, y: 64 },
      { pos: "ZAG", x: 68, y: 75 },
      { pos: "ZAG", x: 32, y: 75 },
      { pos: "LE", x: 14, y: 64 },
      { pos: "VOL", x: 50, y: 56 },
      { pos: "MC", x: 75, y: 44 },
      { pos: "MC", x: 25, y: 44 },
      { pos: "PD", x: 80, y: 24 },
      { pos: "CA", x: 50, y: 14 },
      { pos: "PE", x: 20, y: 24 },
    ],
    Equilibrado: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "LD", x: 86, y: 64 },
      { pos: "ZAG", x: 68, y: 75 },
      { pos: "ZAG", x: 32, y: 75 },
      { pos: "LE", x: 14, y: 64 },
      { pos: "VOL", x: 50, y: 56 },
      { pos: "MC", x: 70, y: 46 },
      { pos: "MEI", x: 30, y: 46 },
      { pos: "PD", x: 80, y: 24 },
      { pos: "CA", x: 50, y: 14 },
      { pos: "PE", x: 20, y: 24 },
    ],
    Ofensivo: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "LD", x: 86, y: 64 },
      { pos: "ZAG", x: 68, y: 75 },
      { pos: "ZAG", x: 32, y: 75 },
      { pos: "LE", x: 14, y: 64 },
      { pos: "MC", x: 50, y: 56 },
      { pos: "MC", x: 75, y: 45 },
      { pos: "MEI", x: 25, y: 40 },
      { pos: "PD", x: 80, y: 24 },
      { pos: "CA", x: 50, y: 14 },
      { pos: "PE", x: 20, y: 24 },
    ],
  },
  "4-4-2": {
    Retranca: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "LD", x: 82, y: 70 },
      { pos: "ZAG", x: 65, y: 72 },
      { pos: "ZAG", x: 35, y: 72 },
      { pos: "LE", x: 18, y: 70 },
      { pos: "MD", x: 82, y: 45 },
      { pos: "VOL", x: 62, y: 55 },
      { pos: "VOL", x: 38, y: 55 },
      { pos: "ME", x: 18, y: 45 },
      { pos: "CA", x: 60, y: 22 },
      { pos: "CA", x: 40, y: 22 },
    ],
    Equilibrado: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "LD", x: 82, y: 68 },
      { pos: "ZAG", x: 65, y: 70 },
      { pos: "ZAG", x: 35, y: 70 },
      { pos: "LE", x: 18, y: 68 },
      { pos: "MD", x: 82, y: 38 },
      { pos: "VOL", x: 62, y: 48 },
      { pos: "MC", x: 38, y: 48 },
      { pos: "ME", x: 18, y: 38 },
      { pos: "CA", x: 60, y: 20 },
      { pos: "CA", x: 40, y: 20 },
    ],
    Ofensivo: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "LD", x: 82, y: 66 },
      { pos: "ZAG", x: 65, y: 68 },
      { pos: "ZAG", x: 35, y: 68 },
      { pos: "LE", x: 18, y: 66 },
      { pos: "VOL", x: 50, y: 56 },
      { pos: "MC", x: 72, y: 46 },
      { pos: "MC", x: 28, y: 46 },
      { pos: "MEI", x: 50, y: 36 },
      { pos: "CA", x: 60, y: 20 },
      { pos: "CA", x: 40, y: 20 },
    ],
  },
  "3-5-2": {
    Retranca: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "ZAG", x: 75, y: 72 },
      { pos: "ZAG", x: 50, y: 75 },
      { pos: "ZAG", x: 25, y: 72 },
      { pos: "MD", x: 85, y: 48 },
      { pos: "VOL", x: 60, y: 56 },
      { pos: "MC", x: 50, y: 40 },
      { pos: "VOL", x: 40, y: 56 },
      { pos: "ME", x: 15, y: 48 },
      { pos: "CA", x: 65, y: 20 },
      { pos: "CA", x: 35, y: 20 },
    ],
    Equilibrado: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "ZAG", x: 75, y: 72 },
      { pos: "ZAG", x: 50, y: 75 },
      { pos: "ZAG", x: 25, y: 72 },
      { pos: "MD", x: 85, y: 46 },
      { pos: "VOL", x: 65, y: 54 },
      { pos: "MEI", x: 50, y: 38 },
      { pos: "MC", x: 35, y: 54 },
      { pos: "ME", x: 15, y: 46 },
      { pos: "CA", x: 65, y: 20 },
      { pos: "CA", x: 35, y: 20 },
    ],
    Ofensivo: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "ZAG", x: 75, y: 72 },
      { pos: "ZAG", x: 50, y: 75 },
      { pos: "ZAG", x: 25, y: 72 },
      { pos: "MD", x: 85, y: 40 },
      { pos: "MC", x: 70, y: 46 },
      { pos: "MEI", x: 50, y: 32 },
      { pos: "MC", x: 30, y: 46 },
      { pos: "ME", x: 15, y: 40 },
      { pos: "CA", x: 65, y: 20 },
      { pos: "CA", x: 35, y: 20 },
    ],
  },
  "5-3-2": {
    Retranca: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "LE", x: 15, y: 70 },
      { pos: "ZAG", x: 35, y: 75 },
      { pos: "ZAG", x: 50, y: 78 },
      { pos: "ZAG", x: 65, y: 75 },
      { pos: "LD", x: 85, y: 70 },
      { pos: "MC", x: 50, y: 44 },
      { pos: "VOL", x: 70, y: 52 },
      { pos: "VOL", x: 30, y: 52 },
      { pos: "CA", x: 65, y: 20 },
      { pos: "CA", x: 35, y: 20 },
    ],
    Equilibrado: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "LE", x: 15, y: 70 },
      { pos: "ZAG", x: 35, y: 75 },
      { pos: "ZAG", x: 50, y: 78 },
      { pos: "ZAG", x: 65, y: 75 },
      { pos: "LD", x: 85, y: 70 },
      { pos: "VOL", x: 70, y: 46 },
      { pos: "MEI", x: 50, y: 38 },
      { pos: "MC", x: 30, y: 46 },
      { pos: "CA", x: 65, y: 20 },
      { pos: "CA", x: 35, y: 20 },
    ],
    Ofensivo: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "LE", x: 15, y: 70 },
      { pos: "ZAG", x: 35, y: 75 },
      { pos: "ZAG", x: 50, y: 78 },
      { pos: "ZAG", x: 65, y: 75 },
      { pos: "LD", x: 85, y: 70 },
      { pos: "MC", x: 70, y: 42 },
      { pos: "MEI", x: 50, y: 32 },
      { pos: "MC", x: 30, y: 42 },
      { pos: "CA", x: 65, y: 20 },
      { pos: "CA", x: 35, y: 20 },
    ],
  },
  "4-2-3-1": {
    Retranca: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "LD", x: 86, y: 64 },
      { pos: "ZAG", x: 68, y: 75 },
      { pos: "ZAG", x: 32, y: 75 },
      { pos: "LE", x: 14, y: 64 },
      { pos: "VOL", x: 60, y: 54 },
      { pos: "VOL", x: 40, y: 54 },
      { pos: "MC", x: 50, y: 38 },
      { pos: "PD", x: 82, y: 36 },
      { pos: "PE", x: 18, y: 36 },
      { pos: "CA", x: 50, y: 14 },
    ],
    Equilibrado: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "LD", x: 86, y: 64 },
      { pos: "ZAG", x: 68, y: 75 },
      { pos: "ZAG", x: 32, y: 75 },
      { pos: "LE", x: 14, y: 64 },
      { pos: "VOL", x: 60, y: 54 },
      { pos: "MC", x: 40, y: 54 },
      { pos: "MEI", x: 50, y: 36 },
      { pos: "PD", x: 75, y: 28 },
      { pos: "PE", x: 25, y: 28 },
      { pos: "CA", x: 50, y: 14 },
    ],
    Ofensivo: [
      { pos: "GOL", x: 50, y: 88 },
      { pos: "LD", x: 86, y: 64 },
      { pos: "ZAG", x: 68, y: 75 },
      { pos: "ZAG", x: 32, y: 75 },
      { pos: "LE", x: 14, y: 64 },
      { pos: "VOL", x: 50, y: 56 },
      { pos: "MEI", x: 50, y: 42 },
      { pos: "MD", x: 75, y: 24 },
      { pos: "ME", x: 25, y: 24 },
      { pos: "PD", x: 80, y: 14 },
      { pos: "CA", x: 50, y: 14 },
    ],
  },
};

export const generatePlayersForTeam = (
  team: string,
  _currentField?: FieldSlot[],
): Player[] => {
  const names = NAMES_BY_TEAM[team] || [];

  const pool: Player[] = names.map((name) => {
    const rating = RATINGS_BY_PLAYER[name] || 75;
    const positions = POSITIONS_BY_PLAYER[name] || ["MC"];
    const jerseyNumber = NUMBERS_BY_PLAYER[name] || 0;

    return {
      id: `${rating}-${Math.random().toString(36).substring(2, 7)}`,
      name: name,
      shortName: name,
      position: positions,
      jerseyNumber: jerseyNumber,
    } as Player;
  });

  return pool.sort((a, b) => {
    const posOrderA = POSITION_ORDER[a.position[0]] || 99;
    const posOrderB = POSITION_ORDER[b.position[0]] || 99;

    if (posOrderA !== posOrderB) {
      return posOrderA - posOrderB;
    }

    const numA = typeof a.jerseyNumber === "number" ? a.jerseyNumber : 99;
    const numB = typeof b.jerseyNumber === "number" ? b.jerseyNumber : 99;

    return numA - numB;
  });
};
