export const POSITIONS = [
  "GOL",
  "LD",
  "ZAG",
  "LE",
  "VOL",
  "MC",
  "MEI",
  "MD",
  "ME",
  "PD",
  "CA",
  "PE",
] as const;

export type Position = (typeof POSITIONS)[number];

export interface PlayerData {
  name: string;
  jerseyNumber: number;
  rating: number;
  positions: Position[];
  edition: number;
}

export const PLAYERS_DB: Record<string, PlayerData[]> = {
  Corinthians: [
    {
      name: "Cássio",
      jerseyNumber: 24,
      rating: 86,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Júlio César",
      jerseyNumber: 1,
      rating: 74,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Danilo Fernandes",
      jerseyNumber: 22,
      rating: 71,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Alessandro",
      jerseyNumber: 2,
      rating: 78,
      positions: ["LD"],
      edition: 2012,
    },
    {
      name: "Welder",
      jerseyNumber: 18,
      rating: 72,
      positions: ["LD"],
      edition: 2012,
    },
    {
      name: "Chicão",
      jerseyNumber: 3,
      rating: 81,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "L. Castán",
      jerseyNumber: 4,
      rating: 83,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Paulo André",
      jerseyNumber: 13,
      rating: 79,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Marquinhos",
      jerseyNumber: 25,
      rating: 74,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Fábio Santos",
      jerseyNumber: 6,
      rating: 80,
      positions: ["LE"],
      edition: 2012,
    },
    {
      name: "Ramon",
      jerseyNumber: 16,
      rating: 73,
      positions: ["LE"],
      edition: 2012,
    },
    {
      name: "Ralf",
      jerseyNumber: 5,
      rating: 84,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Paulinho",
      jerseyNumber: 8,
      rating: 88,
      positions: ["VOL", "MC"],
      edition: 2012,
    },
    {
      name: "Edenílson",
      jerseyNumber: 15,
      rating: 76,
      positions: ["VOL", "LD", "MD"],
      edition: 2012,
    },
    {
      name: "Ramírez",
      jerseyNumber: 14,
      rating: 74,
      positions: ["MEI", "MC"],
      edition: 2012,
    },
    {
      name: "Danilo",
      jerseyNumber: 20,
      rating: 85,
      positions: ["MEI", "MC"],
      edition: 2012,
    },
    {
      name: "Douglas",
      jerseyNumber: 10,
      rating: 79,
      positions: ["MEI"],
      edition: 2012,
    },
    {
      name: "Alex",
      jerseyNumber: 12,
      rating: 82,
      positions: ["MEI"],
      edition: 2012,
    },
    {
      name: "Willian",
      jerseyNumber: 7,
      rating: 78,
      positions: ["PE", "PD"],
      edition: 2012,
    },
    {
      name: "J. Henrique",
      jerseyNumber: 23,
      rating: 80,
      positions: ["PD", "MD"],
      edition: 2012,
    },
    {
      name: "E. Sheik",
      jerseyNumber: 11,
      rating: 86,
      positions: ["PE", "CA", "PD"],
      edition: 2012,
    },
    {
      name: "Romarinho",
      jerseyNumber: 21,
      rating: 78,
      positions: ["PE", "CA"],
      edition: 2012,
    },
    {
      name: "Liédson",
      jerseyNumber: 9,
      rating: 77,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Élton",
      jerseyNumber: 19,
      rating: 73,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Gilsinho",
      jerseyNumber: 17,
      rating: 72,
      positions: ["PD", "PE"],
      edition: 2012,
    },
  ],
  Santos: [
    {
      name: "Rafael",
      jerseyNumber: 1,
      rating: 82,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Aranha",
      jerseyNumber: 12,
      rating: 75,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Vladimir",
      jerseyNumber: 22,
      rating: 70,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Fucile",
      jerseyNumber: 4,
      rating: 78,
      positions: ["LD", "LE"],
      edition: 2012,
    },
    {
      name: "Galhardo",
      jerseyNumber: 23,
      rating: 73,
      positions: ["LD"],
      edition: 2012,
    },
    {
      name: "Edu Dracena",
      jerseyNumber: 2,
      rating: 81,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Durval",
      jerseyNumber: 6,
      rating: 79,
      positions: ["ZAG", "LE"],
      edition: 2012,
    },
    {
      name: "Bruno Rodrigo",
      jerseyNumber: 13,
      rating: 76,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Léo",
      jerseyNumber: 3,
      rating: 77,
      positions: ["LE"],
      edition: 2012,
    },
    {
      name: "Juan",
      jerseyNumber: 15,
      rating: 75,
      positions: ["LE"],
      edition: 2012,
    },
    {
      name: "Arouca",
      jerseyNumber: 5,
      rating: 83,
      positions: ["VOL", "MC"],
      edition: 2012,
    },
    {
      name: "Henrique",
      jerseyNumber: 7,
      rating: 80,
      positions: ["VOL", "ZAG"],
      edition: 2012,
    },
    {
      name: "Adriano",
      jerseyNumber: 16,
      rating: 76,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Ibson",
      jerseyNumber: 14,
      rating: 77,
      positions: ["VOL", "MC"],
      edition: 2012,
    },
    {
      name: "Elano",
      jerseyNumber: 8,
      rating: 79,
      positions: ["MEI", "MC"],
      edition: 2012,
    },
    {
      name: "Ganso",
      jerseyNumber: 10,
      rating: 86,
      positions: ["MEI"],
      edition: 2011,
    },
    {
      name: "F. Anderson",
      jerseyNumber: 20,
      rating: 75,
      positions: ["MEI"],
      edition: 2012,
    },
    {
      name: "G. Magrão",
      jerseyNumber: 17,
      rating: 73,
      positions: ["MEI", "VOL"],
      edition: 2012,
    },
    {
      name: "Bernardo",
      jerseyNumber: 18,
      rating: 74,
      positions: ["MEI", "PE"],
      edition: 2012,
    },
    {
      name: "Neymar",
      jerseyNumber: 11,
      rating: 92,
      positions: ["PE", "CA", "PD"],
      edition: 2011,
    },
    {
      name: "Borges",
      jerseyNumber: 9,
      rating: 80,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Alan Kardec",
      jerseyNumber: 19,
      rating: 79,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Dimba",
      jerseyNumber: 21,
      rating: 70,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "W. Rentería",
      jerseyNumber: 24,
      rating: 72,
      positions: ["CA", "PD"],
      edition: 2012,
    },
    {
      name: "Maranhão",
      jerseyNumber: 25,
      rating: 71,
      positions: ["MD", "LD"],
      edition: 2012,
    },
  ],
  Flamengo: [
    {
      name: "Felipe",
      jerseyNumber: 1,
      rating: 80,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Léo Moura",
      jerseyNumber: 2,
      rating: 81,
      positions: ["LD", "MD"],
      edition: 2012,
    },
    {
      name: "Welinton",
      jerseyNumber: 3,
      rating: 73,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "David Braz",
      jerseyNumber: 4,
      rating: 74,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Willians",
      jerseyNumber: 5,
      rating: 79,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Júnior César",
      jerseyNumber: 6,
      rating: 77,
      positions: ["LE"],
      edition: 2012,
    },
    {
      name: "Deivid",
      jerseyNumber: 7,
      rating: 77,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Renato Abreu",
      jerseyNumber: 8,
      rating: 79,
      positions: ["VOL", "MC", "MEI"],
      edition: 2012,
    },
    {
      name: "Vagner Love",
      jerseyNumber: 9,
      rating: 84,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Ronaldinho",
      jerseyNumber: 10,
      rating: 86,
      positions: ["MEI", "PE"],
      edition: 2012,
    },
    {
      name: "Bottinelli",
      jerseyNumber: 11,
      rating: 76,
      positions: ["MEI", "MC"],
      edition: 2012,
    },
    {
      name: "Paulo Victor",
      jerseyNumber: 12,
      rating: 75,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Maldonado",
      jerseyNumber: 13,
      rating: 75,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "M. González",
      jerseyNumber: 14,
      rating: 77,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Muralha",
      jerseyNumber: 15,
      rating: 71,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Magal",
      jerseyNumber: 16,
      rating: 70,
      positions: ["LE", "VOL"],
      edition: 2012,
    },
    {
      name: "Camacho",
      jerseyNumber: 17,
      rating: 72,
      positions: ["MEI", "MC"],
      edition: 2012,
    },
    {
      name: "Thomás",
      jerseyNumber: 18,
      rating: 73,
      positions: ["MEI", "PE"],
      edition: 2012,
    },
    {
      name: "Gustavo",
      jerseyNumber: 19,
      rating: 71,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Luiz Antônio",
      jerseyNumber: 20,
      rating: 75,
      positions: ["VOL", "MC"],
      edition: 2012,
    },
    {
      name: "Galhardo",
      jerseyNumber: 21,
      rating: 73,
      positions: ["LD"],
      edition: 2012,
    },
    {
      name: "Negueba",
      jerseyNumber: 22,
      rating: 74,
      positions: ["PD", "PE"],
      edition: 2012,
    },
    {
      name: "W. Silva",
      jerseyNumber: 23,
      rating: 72,
      positions: ["LD"],
      edition: 2012,
    },
    {
      name: "Cesar",
      jerseyNumber: 24,
      rating: 68,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Frauches",
      jerseyNumber: 25,
      rating: 69,
      positions: ["ZAG"],
      edition: 2012,
    },
  ],
  Vasco: [
    {
      name: "F. Prass",
      jerseyNumber: 1,
      rating: 83,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Allan",
      jerseyNumber: 2,
      rating: 77,
      positions: ["LD", "VOL", "MD"],
      edition: 2012,
    },
    {
      name: "Rodolfo",
      jerseyNumber: 3,
      rating: 76,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Renato Silva",
      jerseyNumber: 4,
      rating: 77,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Eduardo Costa",
      jerseyNumber: 5,
      rating: 75,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Felipe",
      jerseyNumber: 6,
      rating: 80,
      positions: ["MC", "MEI", "LE"],
      edition: 2012,
    },
    {
      name: "Eder Luis",
      jerseyNumber: 7,
      rating: 80,
      positions: ["PD", "PE"],
      edition: 2012,
    },
    {
      name: "Juninho P.",
      jerseyNumber: 8,
      rating: 84,
      positions: ["MC", "MEI"],
      edition: 2012,
    },
    {
      name: "Alecsandro",
      jerseyNumber: 9,
      rating: 79,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Diego Souza",
      jerseyNumber: 10,
      rating: 83,
      positions: ["MEI", "CA"],
      edition: 2012,
    },
    {
      name: "Tenorio",
      jerseyNumber: 11,
      rating: 78,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Alessandro",
      jerseyNumber: 12,
      rating: 72,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "F. Bastos",
      jerseyNumber: 13,
      rating: 76,
      positions: ["VOL", "MC"],
      edition: 2012,
    },
    {
      name: "Renato Augusto",
      jerseyNumber: 14,
      rating: 71,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Thiago Feltri",
      jerseyNumber: 15,
      rating: 75,
      positions: ["LE"],
      edition: 2012,
    },
    {
      name: "Nilton",
      jerseyNumber: 16,
      rating: 78,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Jumar",
      jerseyNumber: 17,
      rating: 73,
      positions: ["VOL", "LE"],
      edition: 2012,
    },
    {
      name: "W. Barbio",
      jerseyNumber: 18,
      rating: 74,
      positions: ["PD", "PE"],
      edition: 2012,
    },
    {
      name: "Carlos Alberto",
      jerseyNumber: 19,
      rating: 76,
      positions: ["MEI", "MC"],
      edition: 2012,
    },
    {
      name: "Diego Rosa",
      jerseyNumber: 20,
      rating: 71,
      positions: ["MEI"],
      edition: 2012,
    },
    {
      name: "Rômulo",
      jerseyNumber: 21,
      rating: 81,
      positions: ["VOL", "MC"],
      edition: 2012,
    },
    {
      name: "Diogo Silva",
      jerseyNumber: 22,
      rating: 70,
      edition: 2012,
      positions: ["GOL"],
    },
    {
      name: "Fagner",
      jerseyNumber: 23,
      rating: 82,
      positions: ["LD"],
      edition: 2012,
    },
    {
      name: "Fabrício",
      jerseyNumber: 24,
      rating: 72,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Dedé",
      jerseyNumber: 26,
      rating: 86,
      positions: ["ZAG"],
      edition: 2012,
    },
  ],
  Fluminense: [
    {
      name: "Diego Cavalieri",
      jerseyNumber: 12,
      rating: 83,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Ricardo Berna",
      jerseyNumber: 1,
      rating: 73,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Bruno",
      jerseyNumber: 2,
      rating: 76,
      positions: ["LD"],
      edition: 2012,
    },
    {
      name: "Gum",
      jerseyNumber: 3,
      rating: 78,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Anderson",
      jerseyNumber: 4,
      rating: 75,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Carlinhos",
      jerseyNumber: 6,
      rating: 77,
      positions: ["LE"],
      edition: 2012,
    },
    {
      name: "Edinho",
      jerseyNumber: 5,
      rating: 77,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Jean",
      jerseyNumber: 11,
      rating: 79,
      positions: ["VOL", "MC"],
      edition: 2012,
    },
    {
      name: "Deco",
      jerseyNumber: 20,
      rating: 83,
      positions: ["MEI", "MC"],
      edition: 2012,
    },
    {
      name: "Thiago Neves",
      jerseyNumber: 10,
      rating: 82,
      positions: ["MEI", "PE"],
      edition: 2012,
    },
    {
      name: "Wellington Nem",
      jerseyNumber: 17,
      rating: 78,
      positions: ["PE", "PD", "CA"],
      edition: 2012,
    },
    {
      name: "Fred",
      jerseyNumber: 9,
      rating: 85,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Rafael Sóbis",
      jerseyNumber: 23,
      rating: 79,
      positions: ["CA", "PE", "PD"],
      edition: 2012,
    },
    {
      name: "Digão",
      jerseyNumber: 26,
      rating: 72,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Leandro Euzébio",
      jerseyNumber: 14,
      rating: 75,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Wallace",
      jerseyNumber: 13,
      rating: 74,
      positions: ["LD"],
      edition: 2012,
    },
    {
      name: "Thiago Carleto",
      jerseyNumber: 16,
      rating: 71,
      positions: ["LE"],
      edition: 2012,
    },
    {
      name: "Diguinho",
      jerseyNumber: 8,
      rating: 76,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Wagner",
      jerseyNumber: 19,
      rating: 78,
      positions: ["MEI", "MC"],
      edition: 2012,
    },
    {
      name: "Marcos Júnior",
      jerseyNumber: 35,
      rating: 72,
      positions: ["PD", "PE"],
      edition: 2012,
    },
    {
      name: "Samuel",
      jerseyNumber: 18,
      rating: 70,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Valencia",
      jerseyNumber: 21,
      rating: 73,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Felipe",
      jerseyNumber: 22,
      rating: 72,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Lanzini",
      jerseyNumber: 7,
      rating: 75,
      positions: ["MEI"],
      edition: 2012,
    },
    {
      name: "M. Jesus",
      jerseyNumber: 25,
      rating: 71,
      positions: ["ZAG"],
      edition: 2012,
    },
  ],
  Internacional: [
    {
      name: "Muriel",
      jerseyNumber: 1,
      rating: 77,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Nei",
      jerseyNumber: 4,
      rating: 75,
      positions: ["LD"],
      edition: 2012,
    },
    {
      name: "Rodrigo Moledo",
      jerseyNumber: 3,
      rating: 78,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Índio",
      jerseyNumber: 2,
      rating: 76,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Kleber",
      jerseyNumber: 6,
      rating: 78,
      positions: ["LE"],
      edition: 2012,
    },
    {
      name: "Guiñazú",
      jerseyNumber: 5,
      rating: 80,
      positions: ["VOL", "MC"],
      edition: 2012,
    },
    {
      name: "Elton",
      jerseyNumber: 17,
      rating: 74,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "D'Alessandro",
      jerseyNumber: 10,
      rating: 84,
      positions: ["MEI", "MD"],
      edition: 2012,
    },
    {
      name: "Oscar",
      jerseyNumber: 16,
      rating: 85,
      positions: ["MEI", "MC"],
      edition: 2012,
    },
    {
      name: "Dagoberto",
      jerseyNumber: 20,
      rating: 79,
      positions: ["PE", "PD", "CA"],
      edition: 2012,
    },
    {
      name: "Leandro Damião",
      jerseyNumber: 9,
      rating: 84,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Renan",
      jerseyNumber: 12,
      rating: 76,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Juan",
      jerseyNumber: 15,
      rating: 79,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Fabrício",
      jerseyNumber: 13,
      rating: 73,
      positions: ["LE"],
      edition: 2012,
    },
    {
      name: "Tinga",
      jerseyNumber: 7,
      rating: 76,
      positions: ["MC", "MEI"],
      edition: 2012,
    },
    {
      name: "Bolatti",
      jerseyNumber: 8,
      rating: 75,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Jô",
      jerseyNumber: 11,
      rating: 76,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Forlán",
      jerseyNumber: 21,
      rating: 82,
      positions: ["CA", "PE"],
      edition: 2012,
    },
    {
      name: "Datolo",
      jerseyNumber: 19,
      rating: 77,
      positions: ["ME", "MEI"],
      edition: 2012,
    },
    {
      name: "Ygor",
      jerseyNumber: 22,
      rating: 72,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "G. Silva",
      jerseyNumber: 23,
      rating: 73,
      positions: ["LD"],
      edition: 2012,
    },
    {
      name: "Josimar",
      jerseyNumber: 14,
      rating: 71,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Fred",
      jerseyNumber: 18,
      rating: 70,
      positions: ["MEI"],
      edition: 2012,
    },
    {
      name: "Indiozinho",
      jerseyNumber: 24,
      rating: 69,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Bressan",
      jerseyNumber: 25,
      rating: 68,
      positions: ["ZAG"],
      edition: 2012,
    },
  ],
  "Boca Juniors": [
    {
      name: "Agustín Orión",
      jerseyNumber: 1,
      rating: 82,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Sebastián Sosa",
      jerseyNumber: 25,
      rating: 77,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Sebastián D'Angelo",
      jerseyNumber: 12,
      rating: 69,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Rolando Schiavi",
      jerseyNumber: 2,
      rating: 80,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Juan Manuel Insaurralde",
      jerseyNumber: 13,
      rating: 76,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Matías Caruzzo",
      jerseyNumber: 5,
      rating: 76,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Gastón Sauro",
      jerseyNumber: 6,
      rating: 73,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Facundo Roncaglia",
      jerseyNumber: 23,
      rating: 78,
      positions: ["LD", "ZAG"],
      edition: 2012,
    },
    {
      name: "Franco Sosa",
      jerseyNumber: 4,
      rating: 75,
      positions: ["LD"],
      edition: 2012,
    },
    {
      name: "Clemente Rodríguez",
      jerseyNumber: 3,
      rating: 78,
      positions: ["LE", "LD"],
      edition: 2012,
    },
    {
      name: "Enzo Ruiz",
      jerseyNumber: 14,
      rating: 71,
      positions: ["LE", "ZAG"],
      edition: 2012,
    },
    {
      name: "Leandro Somoza",
      jerseyNumber: 18,
      rating: 76,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Cristian Erbes",
      jerseyNumber: 16,
      rating: 74,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Pablo Ledesma",
      jerseyNumber: 8,
      rating: 77,
      positions: ["MC", "MD"],
      edition: 2012,
    },
    {
      name: "Walter Erviti",
      jerseyNumber: 11,
      rating: 77,
      positions: ["ME", "MC"],
      edition: 2012,
    },
    {
      name: "Nicolás Colazo",
      jerseyNumber: 15,
      rating: 74,
      positions: ["ME", "MEI"],
      edition: 2012,
    },
    {
      name: "Juan Román Riquelme",
      jerseyNumber: 10,
      rating: 87,
      positions: ["MEI"],
      edition: 2012,
    },
    {
      name: "Cristian Chávez",
      jerseyNumber: 21,
      rating: 75,
      positions: ["MEI"],
      edition: 2012,
    },
    {
      name: "Guillermo Fernández",
      jerseyNumber: 22,
      rating: 72,
      positions: ["MC", "MD"],
      edition: 2012,
    },
    {
      name: "Pablo Mouche",
      jerseyNumber: 7,
      rating: 78,
      positions: ["PE", "PD"],
      edition: 2012,
    },
    {
      name: "Santiago Silva",
      jerseyNumber: 19,
      rating: 79,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Darío Cvitanich",
      jerseyNumber: 20,
      rating: 79,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Lucas Viatri",
      jerseyNumber: 9,
      rating: 78,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Nicolás Blandi",
      jerseyNumber: 17,
      rating: 76,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Sergio Araujo",
      jerseyNumber: 24,
      rating: 73,
      positions: ["PD", "CA"],
      edition: 2012,
    },
  ],
  "Vélez Sarsfield": [
    {
      name: "Marcelo Barovero",
      jerseyNumber: 1,
      rating: 80,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Germán Montoya",
      jerseyNumber: 13,
      rating: 71,
      positions: ["GOL"],
      edition: 2012,
    },
    {
      name: "Sebastián Domínguez",
      jerseyNumber: 6,
      rating: 79,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Fernando Ortiz",
      jerseyNumber: 4,
      rating: 75,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Fernando Tobio",
      jerseyNumber: 2,
      rating: 74,
      positions: ["ZAG"],
      edition: 2012,
    },
    {
      name: "Fabián Cubero",
      jerseyNumber: 5,
      rating: 77,
      positions: ["LD", "VOL"],
      edition: 2012,
    },
    {
      name: "Eros Medaglia",
      jerseyNumber: 14,
      rating: 68,
      positions: ["LD"],
      edition: 2012,
    },
    {
      name: "Emiliano Papa",
      jerseyNumber: 3,
      rating: 76,
      positions: ["LE"],
      edition: 2012,
    },
    {
      name: "Francisco Cerro",
      jerseyNumber: 18,
      rating: 75,
      positions: ["VOL"],
      edition: 2012,
    },
    {
      name: "Augusto Fernández",
      jerseyNumber: 8,
      rating: 79,
      positions: ["MD", "MC"],
      edition: 2012,
    },
    {
      name: "Héctor Canteros",
      jerseyNumber: 10,
      rating: 76,
      positions: ["MC", "MEI"],
      edition: 2012,
    },
    {
      name: "Federico Insúa",
      jerseyNumber: 22,
      rating: 77,
      positions: ["MEI"],
      edition: 2012,
    },
    {
      name: "Federico Freire",
      jerseyNumber: 19,
      rating: 70,
      positions: ["MC"],
      edition: 2012,
    },
    {
      name: "Iván Bella",
      jerseyNumber: 16,
      rating: 73,
      positions: ["ME", "MD"],
      edition: 2012,
    },
    {
      name: "Brian Ferreira",
      jerseyNumber: 24,
      rating: 70,
      positions: ["MEI", "PE"],
      edition: 2012,
    },
    {
      name: "Juan Manuel Martínez",
      jerseyNumber: 7,
      rating: 81,
      positions: ["PD", "CA"],
      edition: 2012,
    },
    {
      name: "Lucas Pratto",
      jerseyNumber: 12,
      rating: 78,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Mauro Óbolo",
      jerseyNumber: 9,
      rating: 74,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Facundo Ferreyra",
      jerseyNumber: 23,
      rating: 73,
      positions: ["CA"],
      edition: 2012,
    },
    {
      name: "Jonathan Copete",
      jerseyNumber: 25,
      rating: 72,
      positions: ["PE", "PD"],
      edition: 2012,
    },
  ],
  "Corinthians (2013)": [
    {
      name: "Cássio",
      jerseyNumber: 12,
      rating: 82,
      positions: ["GOL"],
      edition: 2013,
    },
    {
      name: "Danilo Fernandes",
      jerseyNumber: 1,
      rating: 72,
      positions: ["GOL"],
      edition: 2013,
    },
    {
      name: "Julio Cesar",
      jerseyNumber: 24,
      rating: 70,
      positions: ["GOL"],
      edition: 2013,
    },
    {
      name: "Alessandro",
      jerseyNumber: 2,
      rating: 75,
      positions: ["LD"],
      edition: 2013,
    },
    {
      name: "Edenílson",
      jerseyNumber: 21,
      rating: 77,
      positions: ["LD", "VOL", "MD"],
      edition: 2013,
    },
    {
      name: "Gil",
      jerseyNumber: 4,
      rating: 80,
      positions: ["ZAG"],
      edition: 2013,
    },
    {
      name: "Paulo André",
      jerseyNumber: 13,
      rating: 77,
      positions: ["ZAG"],
      edition: 2013,
    },
    {
      name: "Chicão",
      jerseyNumber: 3,
      rating: 76,
      positions: ["ZAG"],
      edition: 2013,
    },
    {
      name: "Fábio Santos",
      jerseyNumber: 6,
      rating: 78,
      positions: ["LE"],
      edition: 2013,
    },
    {
      name: "Igor",
      jerseyNumber: 16,
      rating: 69,
      positions: ["LE"],
      edition: 2013,
    },
    {
      name: "Ralf",
      jerseyNumber: 5,
      rating: 81,
      positions: ["VOL"],
      edition: 2013,
    },
    {
      name: "Paulinho",
      jerseyNumber: 8,
      rating: 85,
      positions: ["VOL", "MC"],
      edition: 2013,
    },
    {
      name: "Guilherme",
      jerseyNumber: 20,
      rating: 74,
      positions: ["VOL", "MC"],
      edition: 2013,
    },
    {
      name: "Danilo",
      jerseyNumber: 20,
      rating: 81,
      positions: ["MEI", "MC"],
      edition: 2013,
    },
    {
      name: "Douglas",
      jerseyNumber: 10,
      rating: 76,
      positions: ["MEI"],
      edition: 2013,
    },
    {
      name: "Renato Augusto",
      jerseyNumber: 8,
      rating: 78,
      positions: ["MEI", "MC"],
      edition: 2013,
    },
    {
      name: "Emerson Sheik",
      jerseyNumber: 11,
      rating: 79,
      positions: ["PE", "CA"],
      edition: 2013,
    },
    {
      name: "Romarinho",
      jerseyNumber: 31,
      rating: 76,
      positions: ["PE", "PD"],
      edition: 2013,
    },
    {
      name: "Jorge Henrique",
      jerseyNumber: 23,
      rating: 75,
      positions: ["PD", "MD"],
      edition: 2013,
    },
    {
      name: "Alexandre Pato",
      jerseyNumber: 7,
      rating: 81,
      positions: ["CA", "PD"],
      edition: 2013,
    },
    {
      name: "Guerrero",
      jerseyNumber: 9,
      rating: 82,
      positions: ["CA"],
      edition: 2013,
    },
    {
      name: "Walter",
      jerseyNumber: 18,
      rating: 71,
      positions: ["CA"],
      edition: 2013,
    },
    {
      name: "Willian Arão",
      jerseyNumber: 25,
      rating: 70,
      positions: ["VOL", "MC"],
      edition: 2013,
    },
    {
      name: "Felipe",
      jerseyNumber: 28,
      rating: 72,
      positions: ["ZAG"],
      edition: 2013,
    },
    {
      name: "Giovanni",
      jerseyNumber: 17,
      rating: 69,
      positions: ["MEI"],
      edition: 2013,
    },
  ],
  "Santos (2011)": [
    {
      name: "Rafael",
      jerseyNumber: 1,
      rating: 81,
      positions: ["GOL"],
      edition: 2011,
    },
    {
      name: "Aranha",
      jerseyNumber: 24,
      rating: 72,
      positions: ["GOL"],
      edition: 2011,
    },
    {
      name: "Vladimir",
      jerseyNumber: 26,
      rating: 68,
      positions: ["GOL"],
      edition: 2011,
    },
    {
      name: "Danilo",
      jerseyNumber: 4,
      rating: 80,
      positions: ["LD", "VOL"],
      edition: 2011,
    },
    {
      name: "Pará",
      jerseyNumber: 14,
      rating: 72,
      positions: ["LD"],
      edition: 2011,
    },
    {
      name: "Edu Dracena",
      jerseyNumber: 2,
      rating: 79,
      positions: ["ZAG"],
      edition: 2011,
    },
    {
      name: "Durval",
      jerseyNumber: 6,
      rating: 77,
      positions: ["ZAG", "LE"],
      edition: 2011,
    },
    {
      name: "Bruno Rodrigo",
      jerseyNumber: 21,
      rating: 73,
      positions: ["ZAG"],
      edition: 2011,
    },
    {
      name: "Léo",
      jerseyNumber: 3,
      rating: 75,
      positions: ["LE"],
      edition: 2011,
    },
    {
      name: "Alex Sandro",
      jerseyNumber: 16,
      rating: 79,
      positions: ["LE", "ME"],
      edition: 2011,
    },
    {
      name: "Arouca",
      jerseyNumber: 5,
      rating: 82,
      positions: ["VOL", "MC"],
      edition: 2011,
    },
    {
      name: "Adriano",
      jerseyNumber: 25,
      rating: 73,
      positions: ["VOL"],
      edition: 2011,
    },
    {
      name: "Charles",
      jerseyNumber: 15,
      rating: 70,
      positions: ["VOL"],
      edition: 2011,
    },
    {
      name: "Elano",
      jerseyNumber: 8,
      rating: 80,
      positions: ["MC", "MEI"],
      edition: 2011,
    },
    {
      name: "Ganso",
      jerseyNumber: 10,
      rating: 86,
      positions: ["MEI"],
      edition: 2011,
    },
    {
      name: "F. Anderson",
      jerseyNumber: 20,
      rating: 71,
      positions: ["MEI", "MC"],
      edition: 2011,
    },
    {
      name: "Alan Patrick",
      jerseyNumber: 22,
      rating: 72,
      positions: ["MEI"],
      edition: 2011,
    },
    {
      name: "Possebon",
      jerseyNumber: 17,
      rating: 68,
      positions: ["MC"],
      edition: 2011,
    },
    {
      name: "Neymar",
      jerseyNumber: 11,
      rating: 91,
      positions: ["PE", "CA", "PD"],
      edition: 2011,
    },
    {
      name: "Zé Eduardo",
      jerseyNumber: 20,
      rating: 75,
      positions: ["CA"],
      edition: 2011,
    },
    {
      name: "Borges",
      jerseyNumber: 19,
      rating: 77,
      positions: ["CA"],
      edition: 2011,
    },
    {
      name: "Keirrison",
      jerseyNumber: 9,
      rating: 72,
      positions: ["CA"],
      edition: 2011,
    },
    {
      name: "Maikon Leite",
      jerseyNumber: 7,
      rating: 74,
      positions: ["PD", "PE"],
      edition: 2011,
    },
    {
      name: "Diogo",
      jerseyNumber: 23,
      rating: 69,
      positions: ["PD"],
      edition: 2011,
    },
    {
      name: "Rychely",
      jerseyNumber: 18,
      rating: 67,
      positions: ["PE"],
      edition: 2011,
    },
  ],
};
